name: Quick Checks

on: [push]
permissions:
  contents: read

jobs:
  coverage-report:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Coverage Report"
        run: |
          echo "# Hello World" >> $GITHUB_STEP_SUMMARY


